name: qa4sm_preprocessing
channels:
  - defaults
  - conda-forge
dependencies:
  - python
  - pandas
  - numpy
  - xarray
  - dask
  - netcdf4
  - pyresample
  - scipy
  - pykdtree
  - pip
  - pip:
    - pygeobase
    - parse
    - pygeogrids>=0.4.0
    - pynetcf
    - repurpose>=0.12
    - trollsift
    - pytest-cov
    - pytest
    - matplotlib
    - zarr
    - tqdm
    - chardet
    - cf-xarray
    - sphinx_rtd_theme