name: qa4sm_preprocessing
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - pandas==1.5.3
  - numpy
  - xarray
  - dask
  - netcdf4!=1.6.2
  - pyresample
  - scipy
  - pykdtree
  - pip
  - pip:
    - pygeobase
    - parse
    - pygeogrids>=0.4.0
    - pynetcf
    - repurpose==0.9
    - trollsift
    - pytest-cov
    - pytest
    - matplotlib
    - zarr
    - tqdm
    - chardet
    - cf-xarray==0.8.4
    - sphinx_rtd_theme
