name: qa4sm_preprocessing
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas
  - numpy
  - xarray
  - dask
  - netcdf4
  - pyresample
  - pip
  - pip:
    - pygeobase
    - parse
    - pygeogrids>=0.4.0
    - pynetcf
    - repurpose
    - trollsift
    - pytest-cov
    - pytest
    - matplotlib
    - zarr
